[versions]
material = "1.4.0"
lifecycle = "2.3.1"

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
